# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/US_Baby_Names_right.csv).

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/US_Baby_Names_right.csv')
data

         Unnamed: 0       Id     Name  Year Gender State  Count
0             11349    11350     Emma  2004      F    AK     62
1             11350    11351  Madison  2004      F    AK     48
2             11351    11352   Hannah  2004      F    AK     46
3             11352    11353    Grace  2004      F    AK     44
4             11353    11354    Emily  2004      F    AK     41
...             ...      ...      ...   ...    ...   ...    ...
1016390     5647421  5647422     Seth  2014      M    WY      5
1016391     5647422  5647423  Spencer  2014      M    WY      5
1016392     5647423  5647424     Tyce  2014      M    WY      5
1016393     5647424  5647425   Victor  2014      M    WY      5
1016394     5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 7 columns]

### Step 3. Assign it to a variable called baby_names.

In [ ]:
baby_names = data

### Step 4. See the first 10 entries

In [ ]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [ ]:
baby_names = baby_names.drop(['Unnamed: 0', 'Id'], axis=1)
baby_names

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. Is there more male or female names in the dataset?

In [ ]:
gender_counts = baby_names.groupby('Gender')['Count'].sum()
print(gender_counts)

if gender_counts['M'] > gender_counts['F']:
    print('Có nhiều tên nam hơn tên nữ.')
elif gender_counts['M'] < gender_counts['F']:
    print('Có nhiều tên nữ hơn tên nam.')
else:
    print('Số lượng tên nam và nữ bằng nhau.')

Gender
F    16380293
M    19041199
Name: Count, dtype: int64
Có nhiều tên nam hơn tên nữ.

### Step 7. Group the dataset by name and assign to names

In [ ]:
#names = baby_names.groupby('Name')
names = baby_names.groupby('Name').agg({'Count': 'sum', 'Year': 'first', 'Gender': 'first', 'State': 'first'})
names

### Step 8. How many different names exist in the dataset?

In [ ]:
num_different_names = names.index.nunique()
print("Số tên khác nhau là: ", num_different_names)

Số tên khác nhau là:  17632

### Step 9. What is the name with most occurrences?

In [ ]:

most_name = names['Count'].idxmax()
print("Tên xuất hiện nhiều nhất là: ", most_name)

Tên xuất hiện nhiều nhất là:  Jacob

### Step 10. How many different names have the least occurrences?

In [ ]:

min_count = names['Count'].min()

least_frequent_names = names[names['Count'] == min_count]
print(least_frequent_names)

num_least_frequent_names = len(least_frequent_names)
print("Số lượng tên ít xuất hiện là: ", num_least_frequent_names)

          Count  Year Gender State
Name
Aadarsh       5  2009      M    IL
Aadin         5  2008      M    TX
Aaima         5  2013      F    NY
Aalaya        5  2014      F    CA
Aaminah       5  2004      F    CA
...         ...   ...    ...   ...
Zyien         5  2009      M    TX
Zyire         5  2007      M    NY
Zykeriah      5  2008      F    AL
Zykierra      5  2007      F    GA
Zymari        5  2009      M    NC

[2578 rows x 4 columns]
Số lượng tên ít xuất hiện là:  2578

### Step 11. What is the median name occurrence?

In [ ]:
median_name = names['Count'].median()
print("Số lần xuất hiện tên trung bình là: ", median_name)

Số lần xuất hiện tên trung bình là:  49.0

### Step 12. What is the standard deviation of names?

In [ ]:
std_name = names['Count'].std()
print("Độ lệch chuẩn của tên là: ", std_name)

Độ lệch chuẩn của tên là:  11006.069467891111

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [ ]:
summary = names['Count'].describe()
print(summary)

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64